### ISSUE TITLE
popout strips out base url when deployed to /voila/

### ISSUE THREAD

**Issue by havok2063** [mariobuikhuizen/ipypopout#1]
The popout feature in Jdaviz works when voila is deployed to localhost, e.g. "http://localhost:8000".  The `data-base-url` is set to `/` and the Jdaviz loads fine.  However for our production deployments of Jdaviz embedded,  the Jdaviz popout feature fails to render properly.   

For our deploys, voila is deployed to urls like "http://masttest.stsci.edu/voila".  Our base url is `/voila`.  Without the trailing slash, the popout url is `https://masttest.stsci.edu/voilavoila/templates/ipypopout/static/popout.html?kernelid=81e1412a-72a2-4cc7-ba8b-2113e611d7d1&modelid=2614b11e26884e799e102313ceb8bad6&baseurl=/voila`, which returns a 404 error. 

When I ensure a trailing slash such that the base url is `/voila/` the popout url is `https://masttest.stsci.edu/voila/templates/ipypopout/static/popout.html?kernelid=81e1412a-72a2-4cc7-ba8b-2113e611d7d1&modelid=2614b11e26884e799e102313ceb8bad6&baseurl=/`. which fails to find the correct resource and renders internally a 403 or 404 error.   The base url is getting stripped back to `/`, seemingly here  https://github.com/mariobuikhuizen/ipypopout/blob/e1603515cf641e42f3781b327ddf9d8206736bf6/ipypopout/popout_button.vue#L43

I can manually edit the popout url to the following, which both render Jdaviz successfully.  Either `https://masttest.stsci.edu/voila/templates/ipypopout/static/popout.html?kernelid=81e1412a-72a2-4cc7-ba8b-2113e611d7d1&modelid=2614b11e26884e799e102313ceb8bad6&baseurl=/voila/` 
or 
`https://masttest.stsci.edu/voila/voila/templates/ipypopout/static/popout.html?kernelid=81e1412a-72a2-4cc7-ba8b-2113e611d7d1&modelid=2614b11e26884e799e102313ceb8bad6&baseurl=/voila/` work ok.  

This could be an edge case just for us, but I think there should be some sort of a catch so servers deployed to `/voila/` still work correctly . Or is there a manual hack we could do to get this working for us?

**Comment by havok2063** [comment]
Also, not sure if it matters, but I just noticed this `baseUrl` when I navigated to one of the notebooks, `https://masttest.stsci.edu/voila/render/jdaviz_jwst.ipynb?`.  Should the two base urls match?

```
{ "baseUrl": "/", "kernelId": "2f6790a4-87ce-46f4-bc70-66b5372bb326", "extensions": [ "/voila/nbextensions/bqplot-image-gl/extension.js", "/voila/nbextensions/bqplot/extension.js", "/voila/nbextensions/ipyvolume/extension.js", "/voila/nbextensions/jupyter-datawidgets/extension.js", "/voila/nbextensions/jupyter-golden-layout/extension.js", "/voila/nbextensions/jupyter-matplotlib/extension.js", "/voila/nbextensions/jupyter-splitpanes/extension.js", "/voila/nbextensions/jupyter-threejs/extension.js", "/voila/nbextensions/jupyter-vue/extension.js", "/voila/nbextensions/jupyter-vuetify/extension.js", "/voila/nbextensions/jupyter-webrtc/extension.js" ] }
```

**Comment by mariobuikhuizen** [comment]
Can you try if v0.0.12 fixes this?

**Comment by mariobuikhuizen** [comment]
> Also, not sure if it matters, but I just noticed this baseUrl when I navigated to one of the notebooks, https://masttest.stsci.edu/voila/render/jdaviz_jwst.ipynb?, is set to "/". Should the two base urls match?

The baseUrl from that data is not used in voila-embed, so that shouldn't be a problem.

**Comment by havok2063** [comment]
Ok, I'll test out if v0.0.12 works and will let you know!

**Comment by havok2063** [comment]
ok, that fix worked!  I've pinned our dependency to `ipypopout==0.0.12`.  Thanks @mariobuikhuizen!
