### ISSUE TITLE
404 on the popup page

### ISSUE THREAD

**Issue by laurentm255** [mariobuikhuizen/ipypopout#4]
I can launch a lab or notebook and display `example.ipynb`. The IntSlider and the Button are rendered as expected.
(Note, that I had to comment the `import ipypopout.sync_patch` statement of the first cell : no module `ipypopout.sync_patch` could be found)

When I click the button, a new browser window appears, but with a 404 error message. This URL could not been resolved : `localhost:8888/voila/templates/ipypopout/static/popout.html?kernelid=65140b14-6a46-4586-a700-d30a5033462e&modelid=3bc5eb88a37a417c8843f4fad63fe923&baseurl=/`

I thought I should run `voila` before -> `voila example.ipynb` returns a `jinja2.exceptions.TemplateNotFound: browser-open.html` error :(

Using a lab or a notebook, gives the same result.

Any idea please ?

About my setup :
- Python 3.10 virtual environment (venv)
- `pip install .`
- then `jupyter-lab` or `jupyter notebook`
- Below the version for some modules that might be involved :
ipykernel==6.23.2
ipython==8.14.0
ipyvue==1.9.2
ipyvuetify==1.8.10
ipywidgets==8.0.6
Jinja2==3.1.2
jupyter_client==8.2.0
jupyter_core==5.3.1
jupyter_server==2.6.0
jupyterlab==4.0.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
jupyterlab_server==2.23.0
mistune==2.0.5
nbclassic==1.0.0
nbclient==0.7.4
nbconvert==7.5.0
nbformat==5.9.0
notebook==6.5.4
notebook_shim==0.2.3
Pygments==2.15.1
requests==2.31.0
tornado==6.3.2
traitlets==5.9.0
voila==0.5.0a4
widgetsnbextension==4.0.7

**Comment by mariobuikhuizen** [comment]
I tried to run it in a new environment, and it works for me, I can not reproduce this issue.

We have seen that ad blockers or other protection plugins in the browser can interfere with the popout, maybe you can check if that's happening in your case.

`import ipypopout.sync_patch` can indeed be removed. This was needed for ipywidgets<7.7

**Comment by mariobuikhuizen** [comment]
What is the URL in the browser when you run `example.ipynb`?

**Comment by mariobuikhuizen** [comment]
I can reproduce the issue using the exact versions you specified. Will look into it.

**Comment by mariobuikhuizen** [comment]
It's because of `voila==0.5.0a4`. Can you try with `voila==0.4.0`? (this also requires `jupyterlab<4`)
